DROP TABLE IF EXISTS bookings;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     description VARCHAR(512),
                                     is_available BOOLEAN,
                                     owner_id BIGINT,
                                     request_id BIGINT,
                                     CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     start_date DATE,
                                     end_date DATE,
                                     item_id BIGINT,
                                     booker_id BIGINT,
                                     status VARCHAR(255),
                                     CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description VARCHAR(255) NOT NULL,
                                     requester_id BIGINT NOT NULL,
                                     CONSTRAINT pk_request PRIMARY KEY (id)
);

 ALTER TABLE requests
     ADD CONSTRAINT FK_FRIENDS_FRIENDID FOREIGN KEY (id)
         REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE items
    ADD CONSTRAINT fk_item FOREIGN KEY (id)
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE items
    ADD CONSTRAINT fk_request_item FOREIGN KEY (id)
    REFERENCES requests (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT fk_BOOKING FOREIGN KEY (id)
        REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE bookings
    ADD CONSTRAINT fk_booking_item FOREIGN KEY (id)
    REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE;